<?php

namespace Just\Shapeshifter\Exceptions;

class ValidationException extends \Exception
{
    /**
     * Validation errors
     *
     * @var Messagebag
     */
    protected $errors;

    /**
     * @param string    $errors
     * @param string    $message
     * @param int       $code
     * @param Exception $previous
     */
    public function __construct($errors, $message = '', $code = 0, Exception $previous = null)
    {
        $this->errors = $errors;

        parent::__construct($message, $code, $previous); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function getErrors()
    {
        return $this->errors;
    }
}
